# Generated by Django 6.0 on 2026-04-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
